Console.WriteLine("Введи имя");
string naming = Console.ReadLine();
Console.WriteLine("Введи возраст");
int age = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введи почту");
string email = Console.ReadLine();
Console.WriteLine("Количество баллов по кодингу, через запятую");
double prog = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Количество баллов по математике, через запятую");
double math = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("Количество баллов по физике, через запятую");
double physic = Convert.ToDouble(Console.ReadLine());
double summary = (prog + math + physic);
double middle_sum = summary / 3;
string pattern = $" Ф.И.О: {naming} \nВозраст: {age} \nEmail: {email} \nБаллы по программированию: {prog} \nБаллы по математике: {math} \nБаллы по физике: {physic} \nОбщий балл: {summary} \nСредний балл: {middle_sum}";
Console.WriteLine(pattern);
